### ISSUE TITLE
Add documentation where to get container images from

### ISSUE THREAD

**Issue by dvonessen** [dbsystel/gitlab-ci-python-library#11]
As far as I know, there are two sources of truth for container images. 
Github registry and docker registry. We should document how to get the container and run it.

**Comment by ThomasSteinbach** [comment]
I removed the obsolete image build on github with PR #17 . There is no need to have this inconvenient and double image artifact.

**Comment by ThomasSteinbach** [comment]
The documentation of how to use the docker image is written into the user documentation. Have a look here:
https://dbsystel.github.io/gitlab-ci-python-library/user/index.html#_configuring_your_project_to_use_gcip

The docker image is primarily made for exact that use case described there.

**Comment by ThomasSteinbach** [comment]
@dvonessen would both solve this issue for you?

**Comment by dvonessen** [comment]
Thank you for pointing to the documentation.
Yes that closes the issue.
